#!/bin/bash

echo "🎉 Bienvenue dans Happipet!"
echo ""
echo "📱 Pour lancer l'application Expo, choisissez une option:"
echo ""
echo "1️⃣  Lancer sur iOS (simulateur)"
echo "   -> npm run ios"
echo "   -> ou: expo start --ios"
echo ""
echo "2️⃣  Lancer sur Android (émulateur)"
echo "   -> npm run android"
echo "   -> ou: expo start --android"
echo ""
echo "3️⃣  Lancer sur Web (navigateur)"
echo "   -> npm run web"
echo "   -> ou: expo start --web"
echo ""
echo "4️⃣  Lancer le serveur de développement interactif"
echo "   -> npm start"
echo "   -> ou: expo start"
echo ""
echo "Après le lancement:"
echo "  • Appuyez sur 'r' pour recharger l'application"
echo "  • Appuyez sur 'i' pour ouvrir sur iOS"
echo "  • Appuyez sur 'a' pour ouvrir sur Android"
echo "  • Appuyez sur 'w' pour ouvrir sur le web"
echo "  • Appuyez sur 'c' pour effacer le cache"
echo ""
echo "Documentation: https://docs.expo.dev/"
